name: CI de Acessibilidade

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # Instalar dependências do Chromium para o ambiente headless
    - name: Instalar dependências do Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 libatk-bridge2.0-0 libxkbcommon-x11-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm-dev libpango-1.0-0 libpangocairo-1.0-0 libatk1.0-0 libcups2 libdrm-dev libxkbcommon-dev libxrandr-dev libxcb-composite0 libxcb-randr0 libxcb-xfixes0 libxshmfence-dev libharfbuzz-icu-dev libwebp-dev libxml2-dev libxslt1-dev libgdk-pixbuf2.0-0

    - name: Instalar Pa11y
      run: npm install -g pa11y # Instala o Pa11y globalmente

    - name: Servir arquivos HTML localmente
      run: |
        npm install -g http-server
        http-server . & # Inicia um servidor na porta 8080 em background
        sleep 5 # Dá um tempo para o servidor iniciar

    - name: Executar Testes de Acessibilidade com Pa11y
      run: |
        echo "Iniciando testes de acessibilidade em arquivos HTML locais..."
        pa11y http://localhost:8080/index.html --standard WCAG2AA
        pa11y http://localhost:8080/saber-literário/cadastrar-livro.html --standard WCAG2AA
        pa11y http://localhost:8080/saber-literário/catalogo.html --standard WCAG2AA
        pa11y http://localhost:8080/saber-literário/home.html --standard WCAG2AA
        pa11y http://localhost:8080/saber-literário/login.html --standard WCAG2AA
