name: CI de Acessibilidade

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar Pa11y
      run: npm install -g pa11y # Instala o Pa11y globalmente

    - name: Servir arquivos HTML localmente
      run: |
        npm install -g http-server
        http-server . & # Inicia um servidor na porta 8080 em background
        sleep 5 # Dá um tempo para o servidor iniciar

    - name: Executar Testes de Acessibilidade com Pa11y
      env: # <--- NOVA SEÇÃO: Definindo variáveis de ambiente para o Puppeteer
        PUPPETEER_LAUNCH_ARGS: "--no-sandbox" # <--- Passa a flag --no-sandbox para o Puppeteer
      run: |
        echo "Iniciando testes de acessibilidade em arquivos HTML locais..."
        pa11y http://localhost:8080/index.html --standard WCAG2AA
        pa11y http://localhost:8080/saber-literário/cadastrar-livro.html --standard WCAG2AA
        pa11y http://localhost:8080/saber-literário/catalogo.html --standard WCAG2AA
        pa11y http://localhost:8080/saber-literário/home.html --standard WCAG2AA
        pa11y http://localhost:8080/saber-literário/login.html --standard WCAG2AA
