name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', se esse for o caso

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Deploy com peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Ajuste se os arquivos estiverem em outra pasta
