name: De olho nos erros ortográficos

on: push

jobs:
  verificar-ortografia:
    runs-on: ubuntu-latest
    steps:
      - name: Verificação do código
        uses: actions/checkout@v3

      - name: Instalar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar verificação ortográfica
        run: npm install -g cspell

      - name: Verificar erros de ortografia no HTML
        run: cspell "**/*.html"